# Generated by Django 5.1 on 2024-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='year_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
